baseURL = 'https://akzn.me/'
title = 'Ayushman Khazanchi'
enableGitInfo = true    # required for lastmod to work

languageCode = 'en'
DefaultContentLanguage = "en"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

theme = 'Anatole'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe=true

    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'dracula'
        tabWidth = 4

[params]
    title = "Ayushman Khazanchi"
    author = "Ayushman Khazanchi"
    profilePicture = "images/me.png"
    description = """Software & DevOps Engineer.
    """
    headerImg = "images/mariannizmo.png" # defined and used in themes/anatole/layouts/partials/head.html
    
    #copyright = "2020-{{ YEAR }}" # default is current year

    keywords = ""
    favicon = "favicons/"
    # example ["css/custom.css"]
    customCss = ["css/syntax.css", "css/styles.css"]
    # example ["js/custom.js"]
    customJs = [] 
    doNotLoadAnimations = true

    # Date settings
    singleDateFormat = "Jan 2, 2006"
    indexDateFormat = "Jan 2, 2006"
    listDateFormat = "Jan 2, 2006"

    # Google Fonts
    googleFonts = ["PT+Serif", "PT+Sans+Narrow:wght@400;700", "Fira+Mono"]
    # Google Site Verify
    #googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

    # Enable Disqus
    #disqusShortname = ""

    # Google Analytics
    #googleAnalytics = "UA-123-45"

    # static page as main page instead of list of posts
    mainSections = []

    images = ["images/me.png"]

    # postSectionName = "blog"
    fullPostContent = false     # disable full posts on home page
    readMore = true     # enable truncated posts to have read-more link
    reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'
    enableMediumZoom = true     # enable medium-like zoom on images

    contentratio = 0.8      # smaller sidebar
    hidesidebar = false      # don't hide sidebar on content pages

    # Related posts
    #relatedPosts = true
    #numberOfRelatedPosts = 3
    
    rssFullContent = true

    # Get syntax highlighting
    pygmentsCodeFences = true
    pygmentsUseClasses = true
    pygmentsCodefencesGuessSyntax = true

    [related]
        includeNewer = true
        threshold = 80
        toLower = true
        [[related.indices]]
            name = 'keywords'
            weight = 100
        [[related.indices]]
            name = 'tags'
            weight = 80
    
    [taxonomies]
        category = "categories"
        series = "series"
        tag = "tags"

    # Twitter cards
    [social]
        twitter = "aykhazanchi"
        images = ["images/mariannizmo.png"]

    [[params.socialIcons]]
        icon = "fas fa-envelope"
        title = "e-mail"
        url = "mailto:aykhazanchi@gmail.com"
    [[params.socialIcons]]
        icon = "fab fa-github"
        title = "github"
        url = "https://github.com/aykhazanchi"
    [[params.socialIcons]]
        icon = "fab fa-linkedin"
        title = "linkedin"
        url = "https://linkedin.com/in/aykhazanchi"
    [[params.socialIcons]]
        icon = "fab fa-instagram"
        title = "instagram"
        url = "https://instagram.com/aykhazanchi"
    [[params.socialIcons]]
        icon = "fab fa-goodreads"
        title = "goodreads"
        url = "https://www.goodreads.com/aykhazanchi"
    [[params.socialIcons]]
        icon = "fa-solid fa-rss"
        title = "rss"
        url = "https://www.akzn.me/blog/index.xml"

[menu]
    [[menu.main]]
        name = "Home"
        identifier = "home"
        weight = 100
        url = "/"

    [[menu.main]]
        name = "About"
        weight = 200
        identifier = "about"
        url = "/about/"

    [[menu.main]]
        name = "Code"
        weight = 300
        identifier = "code"
        url = "/code/"

    [[menu.main]]
        name = "Blog"
        weight = 500
        identifier = "blog"
        url = "/blog/"

    [[menu.main]]
        name = "Food"
        weight = 600
        identifier = "food"
        url = "/food/"
    
    [[menu.main]]
        name = "Travel"
        weight = 700
        identifier = "travel"
        url = "/travel/"

    [[menu.main]]
        name = "Likes"
        weight = 800
        identifier = "likes"
        url = "/likes/"

    [[menu.main]]
        name = "Now"
        weight = 900
        identifier = "now"
        url = "/now/"

    [[menu.footer]]
        name = "Copyright Ayushman Khazanchi"
        weight = 1000
        identifier = "copyright"
        url = "/copyright/"